### ISSUE TITLE
Auto-validate @p entry, even if no tilde is included

### ISSUE THREAD

**Issue by urcades** [urbit/bitcoin-wallet#11]
Galen Feedback:
- If I paste in a planet name with no ~ into the ‘To’ field I get an error. Can we prepend a ~ or try to validate as a @p without one?

We should handle this in a similar manner to landscape's handling of PatP search/filtering.

**Comment by jalehman** [comment]
This is also the case with master tickets and hyphens—you've got to enter them. I really like how the Bridge master ticket input "just works" wrt this formatting.

**Comment by finned-palmer** [comment]
This has been merged.
