### ISSUE TITLE
I should see that my balance is being determined when connecting to a provider

### ISSUE THREAD

**Issue by urcades** [urbit/bitcoin-wallet#17]
Ideally this would provide feedback to the user as to how much progress had made, i.e. a progress bar. We can only really do this though if we're using a blockfilter-based approach, but that results in a pretty big performance hit.

The other approach is to tell the user how many addresses have been scanned so far, which doesn't tell you how long it'll take precisely, but the user will have some idea of how many addresses they've utilized most likely.

**Comment by finned-palmer** [comment]
Starting on this.

**Comment by urcades** [comment]
A relatively simple "indeterminate loader" take on this:

<img width="1155" alt="Screen Shot 2021-07-09 at 3 59 09 AM" src="https://user-images.githubusercontent.com/1195363/125044514-0598fe80-e06a-11eb-842e-4dba5cada646.png">

I'm unsure exactly what "Address-scanning" processes look like with wallets, but another version of this, with an actual endpoint could be rendered as such:

<img width="1024" alt="Screen Shot 2021-07-09 at 4 01 54 AM" src="https://user-images.githubusercontent.com/1195363/125044880-66c0d200-e06a-11eb-9e4a-ad25f8072fc6.png">

**Comment by finned-palmer** [comment]
This has been merged.
