### ISSUE TITLE
Make signing with Bridge the primary flow

### ISSUE THREAD

**Issue by jalehman** [urbit/bitcoin-wallet#19]
Right now signing with a master ticket is primary, which is a much smoother flow for demos, but is also fairly dangerous. Let's do two things:

1. Make **Sign with Bridge** the default option.
2. Add a disclaimer when in **Sign with Master Key** that this is action is unsafe.

**Comment by ynx0** [comment]
Just curious, what makes signing with master key less safe? Is it because there is a the potential for it to be leaked?
