### ISSUE TITLE
Cannot navigate back to Landscape from BTC wallet on Port

### ISSUE THREAD

**Issue by bioy-casares** [urbit/bitcoin-wallet#23]
Cannot navigate back to Landscape from BTC wallet when using Port.  Port does not offer a URL bar where you could clip the  "/~btc" off the end of the URL. Neither is there an (X) button to exit Bitcoin wallet.  Launch Bitcoin Wallet on Port to reproduce.

**Comment by urcades** [comment]
Duplicate of #9 , but noted, and fully acknowledged
