### ISSUE TITLE
btc-wallet "copy address" button doesn't work

### ISSUE THREAD

**Issue by belisarius222** [urbit/bitcoin-wallet#36]
**Describe the bug**
Clicking the "Copy Address" button in the btc-wallet app does not copy anything to the clipboard, on either mobile or desktop.  Clicking the address also had no noticeable effect.  I captured a screensot of a console error from the desktop, which was produced each time I clicked on either the bitcoin address itself or the "Copy Address" button.

For extra context, my btc wallet was initiated from my ship's master ticket, and I had just selected a provider immediately before trying to copy this address.

**Screenshots**
![image](https://user-images.githubusercontent.com/874741/123346036-603c4180-d525-11eb-9be1-953ac239eb72.png)
**Desktop (please complete the following information):**
 - OS: macos
 - Browser: chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS
 - Browser: chrome

**Comment by finned-palmer** [comment]
Also grabbing this.

**Comment by finned-palmer** [comment]
This fix has been merged.
