### ISSUE TITLE
Visual regression in USD pricing printing

### ISSUE THREAD

**Issue by urcades** [urbit/bitcoin-wallet#41]
Currently, it appears as though our display of USD currency counts in the bitcoin wallet has regressed a bit:

<img width="396" alt="Screen Shot 2021-07-19 at 2 52 47 PM" src="https://user-images.githubusercontent.com/1195363/126212143-c71297d4-eda3-4215-b4df-1fb9db5cbd88.png">

Displaying currency amounts should appear as such: `$83.47`

Or, as displayed in the latest designs:

<img width="597" alt="Screen Shot 2021-07-19 at 2 55 31 PM" src="https://user-images.githubusercontent.com/1195363/126212350-97964cfc-32db-4402-aa80-9b02180263ae.png">

**Comment by finned-palmer** [comment]
Hey @urcades this is actually fixed in the `release/bitcoin-wallet` branch already: https://github.com/urbit/urbit/pull/5096
