### ISSUE TITLE
btc-wallet spawns new Bridge tabs at ~1m intervals

### ISSUE THREAD

**Issue by yapishu** [urbit/bitcoin-wallet#42]
I sent some BTC to another ship, and once I got to the signing portion of the transaction and clicked 'Sign with Bridge', my browser began spamming new tabs that redirected to the Bridge signing URL. These tabs would open 3 at a time, appx. once a minute. When I opened a second tab with btc-wallet, that tab also spawned new Bridge tabs. This behavior persisted until the transaction cleared and I closed the window, perhaps 10 minutes.  

Using current Brave (Chromium)

**Comment by finned-palmer** [comment]
Thanks, looking into it now.
