### ISSUE TITLE
Standalone BTC Wallet will not start up

### ISSUE THREAD

**Issue by urcades** [urbit/bitcoin-wallet#44]
Currently, on the recently-updated network, the bitcoin wallet app simply fails to resolve or display an interface.

This is the error I'm seeing in the web console:

<img width="639" alt="Screen Shot 2021-09-30 at 3 07 53 PM" src="https://user-images.githubusercontent.com/1195363/135515917-2c550051-97f0-435b-ac8f-55a4324adeb6.png">

Bitcoin desk info:

```
%bitcoin
  /sys/kelvin:      [%zuse 420]
  base hash:        0v15.309sf.6l1bk.l6bh6.c142e.of3jg.tbna0.qehna.4go0u.ceq25.8kkfo
  %cz hash:         0v15.309sf.6l1bk.l6bh6.c142e.of3jg.tbna0.qehna.4go0u.ceq25.8kkfo
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~mister-dister-dozzod-dozzod]
  updates:          tracking
  source ship:      ~sabbus
  source desk:      %bitcoin
  source aeon:      2
  pending updates:  ~
::
%base
```

**Comment by finned-palmer** [comment]
For now, this is the fix if you run into this:
`|nuke %btc-wallet` and then `|rein %bitcoin [& %btc-wallet]`

Same thing can be done with %btc-provider.

**Comment by eamsden** [comment]
@finned-palmer tried this procedure and I still cannot reconnect. I get

```
error in %btc-wallet
%watch-not-unique
! subscribe wire not unique
! %btc-wallet
! /set-provider/~matwet
! [p=~matwet q=%btc-provider]
```

in dojo

**Comment by finned-palmer** [comment]
@eamsden saw a similar issue on my wife's planet, but it turned out to be an issue with ~matwet. I pointed it at my own provider and it worked. Can you try setting `~finned-palmer` as your provider (I've added you to the whitelist)?

**Comment by famousj** [comment]
Here's the problem I'm having:
- I setup the node
- I import the xpub
It looks successful, but it says it has no transactions and doesn't show a wallet address.

Then if I refresh the page, bad things happen:
```
%watch-not-unique
! subscribe wire not unique
! %btc-wallet
! /set-provider/~faster-wallet-dozzod-matwet
! [p=~faster-wallet-dozzod-matwet q=%btc-provider]
```

The page asks for my xpub again.  I provide that.  Dojo says
```
xpub already in wallet
```

And it spins forever.  Refreshing doesn't fix it.

Can I just setup my wallet in the dojo?

**Comment by finned-palmer** [comment]
you may need to clear out your xpubs via dojo. run `:btc-wallet +dbug`. if you see more thane one xpub there you can delete them with: `:btc-wallet|command %delete-wallet xpub=<the xpub you want to delete>`

**Comment by famousj** [comment]
The reason I have two xpubs is the app is in a weird state where the web app is asking for an xpub again.  So I enter it again and it rejects it because it already has one.

**Comment by famousj** [comment]
Further detail: after I connect, I'm getting a null wallet.

**Comment by finned-palmer** [comment]
Yeah, I've heard about some people getting into this state before. Do you have any console output from your browser that you could share?

Also, does your xpub start with an 'x' or a 'z', or does it start with some other letter? A few weeks ago the bridge was giving everyone 'vpubs' (testnet keys), and it caused the issue you're describing for some people.

**Comment by famousj** [comment]
Yes!  My xpub starts with "v".  I'll grab that off bridge again and try it out.

**Comment by finned-palmer** [comment]
Yep, that's the issue.

**Comment by finned-palmer** [comment]
I think we can safely close this.
